### PR TITLE
Translation improvement for PT-BR

### PR DESCRIPTION
**Pull request by vitordagamagodoy**
I made some changes to make text clearer in PT-BR. By the way, there is a lot of work left. Can I continue the translation?

### CODE REVIEW

**Review by danielfireman — APPROVED** [review]
@dgryski hope you don't mind. Chiming in just to have another pair of ptbr eyes.

@vitordagamagodoy Cool stuff, thanks! LGTM. :+1: 

Yeah, there is a lot of work left and we could actually share and cross review it if you don't mind. I've already started the section II (How to optimize) and I could send a PR by the end of the week. Is that ok?

We could update #17 when we start working on a section to avoid re-work. How does that sound, @vitordagamagodoy ?

**Comment by vitordagamagodoy** [comment]
Sounds good!

**Comment by dgryski** [comment]
Just let me know when you want this merged to master.

**Comment by vitordagamagodoy** [comment]
That was my last commit in this PR. You can merge it anytime :)

**Pull request merged**
