### PR TITLE
Add Brazilian Portuguese to available translations

### PR DESCRIPTION
**Pull request by danielfireman**
Now that we completed the translation of the book, it is time to promote it :D

Thanks @dgryski for the excellent material and @dialmformart for all the work on the PT-BR translation!

### CODE REVIEW

**Comment by danielfireman** [comment]
Not sure why the `performance-ptbr.md` got pulled into this PR. Sorry for that. CLosing this PR and opening a new one.

**Comment by dgryski** [comment]
Because I merged a bit too early and there was an extra grammar fix that came in, then I tried to "fix" it by merging by hand, but then I force-pushed, and .. well ... stuff broke.  Sorry..

**Comment by dgryski** [comment]
I'll update the README by hand.  Don't worry about a PR.

**Comment by danielfireman** [comment]
No problem, everything is sorted out now! Thanks again for the excellent material!

**Pull request closed without merging**
