### PR TITLE
Adding a note on benchmarking on the correct target platform

### PR DESCRIPTION
**Pull request by StabbyCutyou**
@dgryski was reading through the doc, and noticed something I felt was missing from the notes on the proper benchmarking approach. 

Happy to update the language, or you can simply make the change if you think it makes sense.

### CODE REVIEW

**Comment by StabbyCutyou** [comment]
Yea, I would definitely agree there, but I didn't wanna build up a big paragraph in what felt like should be a short hit-list of things to think about.

Likely makes sense as it's own section about proper benchmarking as a concept.

**Comment by StabbyCutyou** [comment]
Specifically why benching on a dev machine (which is full of processes in the background all competing for cpu, io, and memory) is way different from a single-purpose virtual node in something like AWS, or from inside a docker container - much more so than benchmarking (to use AWS parlance) code on an M4 when you'd be running it on a C3.2xl would be.

**Comment by dgryski** [comment]
Then maybe we can make the bullet point shorter, and add a note to expand on this in the benchmarking section.

**Comment by StabbyCutyou** [comment]
Thumbsup.tiff

Just wanted to make sure that point was added - totally at the authors
discretion as to how best to make the point :)

**Pull request merged**
